[[Qt6Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c22c6f39706cd6118ed9d383078043958ecc4adc"
lazy = true
libc = "musl"
llvm_version = "20"
os = "linux"

    [[Qt6Tools.download]]
    sha256 = "8f779a4d6d5fe1a44990f6433899ded24573476b0fca7943d827e9a6fb901a2a"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Tools_jll.jl/releases/download/Qt6Tools-v6.8.2+1/Qt6Tools.v6.8.2.x86_64-linux-musl-cxx11-llvm_version+20.tar.gz"
[[Qt6Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84ecd251d0cb6e00f6f39a787fc0f81fe3e985ac"
lazy = true
libc = "musl"
llvm_version = "20.asserts"
os = "linux"

    [[Qt6Tools.download]]
    sha256 = "3024edaa5d642db4d9c6dca4f5c21eae6e2d568dcb3c67ae40780ddb5458220a"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Tools_jll.jl/releases/download/Qt6Tools-v6.8.2+1/Qt6Tools.v6.8.2.x86_64-linux-musl-cxx11-llvm_version+20.asserts.tar.gz"
