# Autogenerated wrapper script for Qt6Tools_jll for x86_64-linux-musl-cxx11-llvm_version+20.asserts
export assistant, designer, linguist, pixeltool, qdbus, qdbusviewer, qdistancefieldgenerator, qdoc, qtdiag, qtplugininfo

using Expat_jll
using Qt6Base_jll
using Qt6Declarative_jll
using Clang_jll
JLLWrappers.@generate_wrapper_header("Qt6Tools")
JLLWrappers.@declare_executable_product(assistant)
JLLWrappers.@declare_executable_product(designer)
JLLWrappers.@declare_executable_product(linguist)
JLLWrappers.@declare_executable_product(pixeltool)
JLLWrappers.@declare_executable_product(qdbus)
JLLWrappers.@declare_executable_product(qdbusviewer)
JLLWrappers.@declare_executable_product(qdistancefieldgenerator)
JLLWrappers.@declare_executable_product(qdoc)
JLLWrappers.@declare_executable_product(qtdiag)
JLLWrappers.@declare_executable_product(qtplugininfo)
function __init__()
    JLLWrappers.@generate_init_header(Expat_jll, Qt6Base_jll, Qt6Declarative_jll, Clang_jll)
    JLLWrappers.@init_executable_product(
        assistant,
        "bin/assistant",
    )

    JLLWrappers.@init_executable_product(
        designer,
        "bin/designer",
    )

    JLLWrappers.@init_executable_product(
        linguist,
        "bin/linguist",
    )

    JLLWrappers.@init_executable_product(
        pixeltool,
        "bin/pixeltool",
    )

    JLLWrappers.@init_executable_product(
        qdbus,
        "bin/qdbus",
    )

    JLLWrappers.@init_executable_product(
        qdbusviewer,
        "bin/qdbusviewer",
    )

    JLLWrappers.@init_executable_product(
        qdistancefieldgenerator,
        "bin/qdistancefieldgenerator",
    )

    JLLWrappers.@init_executable_product(
        qdoc,
        "bin/qdoc",
    )

    JLLWrappers.@init_executable_product(
        qtdiag,
        "bin/qtdiag",
    )

    JLLWrappers.@init_executable_product(
        qtplugininfo,
        "bin/qtplugininfo",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
